// Layer FULLYCONNECTED2
#define FULLYCONNECTED2_IN_FEATURES 100
#define FULLYCONNECTED2_OUT_FEATURES 24

// Layer FULLYCONNECTED1
#define FULLYCONNECTED1_IN_FEATURES 100
#define FULLYCONNECTED1_OUT_FEATURES 100

#define FULLYCONNECTED1_PREV_LAYER_INPUT_SIZE 24

// Layer FULLYCONNECTED0
#define FULLYCONNECTED0_IN_FEATURES 4096
#define FULLYCONNECTED0_OUT_FEATURES 100

#define FULLYCONNECTED0_PREV_LAYER_INPUT_SIZE 100


const int weights_DDR_OFFSET0 = 0; 
const int weights_DDR_OFFSET1 = FULLYCONNECTED0_OUT_FEATURES * FULLYCONNECTED0_IN_FEATURES;
const int weights_DDR_OFFSET2 = weights_DDR_OFFSET1 + FULLYCONNECTED1_OUT_FEATURES * FULLYCONNECTED1_IN_FEATURES;
//const int weights_DDR_OFFSET3 = weights_DDR_OFFSET1 + FULLYCONNECTED2_OUT_FEATURES * FULLYCONNECTED2_IN_FEATURES;


const int bias_DDR_OFFSET0 = FULLYCONNECTED0_OUT_FEATURES;
const int bias_DDR_OFFSET1 = bias_DDR_OFFSET0 + FULLYCONNECTED1_OUT_FEATURES;
const int bias_DDR_OFFSET2 = bias_DDR_OFFSET1 + FULLYCONNECTED2_OUT_FEATURES;

const int gradients_DDR_OFFSET0 = 0
const int gradients_DDR_OFFSET1 = (FULLYCONNECTED0_OUT_FEATURES * FULLYCONNECTED0_IN_FEATURES) + FULLYCONNECTED0_OUT_FEATURES;
const int gradients_DDR_OFFSET2 = gradients_DDR_OFFSET1 + (FULLYCONNECTED1_OUT_FEATURES * FULLYCONNECTED1_IN_FEATURES) + FULLYCONNECTED1_OUT_FEATURES;
